### ISSUE TITLE
error in babel after install through 

### ISSUE THREAD

**Issue by GrandM1961** [leotiger/grav-plugin-babel#13]
I get this error now right after installation in terminal with bin/gpm install babel:

Whoops \ Exception \ ErrorException (E_COMPILE_ERROR)
Declaration of Grav\Plugin\Babel\BabelConnector::query($query) must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs): PDOStatement|false

**Comment by masetto** [comment]
I have the same error. 
@GrandM1961 did you solve it?

**Comment by leotiger** [comment]
Sorry for not coming back here for a long time. The error should be fixed in version 1.1.4.

**Comment by leotiger** [comment]
Should be fixed in with version v1.1.4
